/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.yakut.azone.gui;

/**
 *
 * @author Hp
 */
public class Hakkinda extends javax.swing.JPanel {

          /**
           * Creates new form Hakkinda
           */
          public Hakkinda() {
                    initComponents();
          }

          public void init() {
 
                  
          }

          /**
           * This method is called from within the constructor to initialize the
           * form. WARNING: Do NOT modify this code. The content of this method
           * is always regenerated by the Form Editor.
           */
          @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jToolBar1 = new javax.swing.JToolBar();
                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jButton4 = new javax.swing.JButton();
                jButton5 = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();

                setBackground(new java.awt.Color(41, 45, 49));

                jToolBar1.setFloatable(false);
                jToolBar1.setRollover(true);

                jButton1.setForeground(new java.awt.Color(255, 255, 255));
                jButton1.setText("UzmanPDKS");
                jButton1.setFocusable(false);
                jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jButton1.setPreferredSize(new java.awt.Dimension(100, 100));
                jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jToolBar1.add(jButton1);

                jButton2.setForeground(new java.awt.Color(255, 255, 255));
                jButton2.setText("AgsisOGS");
                jButton2.setFocusable(false);
                jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jButton2.setPreferredSize(new java.awt.Dimension(100, 100));
                jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jToolBar1.add(jButton2);

                jButton3.setForeground(new java.awt.Color(255, 255, 255));
                jButton3.setText("Stadyum");
                jButton3.setFocusable(false);
                jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jButton3.setPreferredSize(new java.awt.Dimension(100, 100));
                jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jToolBar1.add(jButton3);

                jButton4.setForeground(new java.awt.Color(255, 255, 255));
                jButton4.setText("Yemekhane");
                jButton4.setFocusable(false);
                jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jButton4.setPreferredSize(new java.awt.Dimension(100, 100));
                jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jToolBar1.add(jButton4);

                jButton5.setForeground(new java.awt.Color(255, 255, 255));
                jButton5.setText("Access");
                jButton5.setFocusable(false);
                jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jButton5.setPreferredSize(new java.awt.Dimension(100, 100));
                jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jToolBar1.add(jButton5);

                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/yakut/resource/ecc-w.png"))); // NOI18N
                jLabel2.setText("www.eccsistem.com");
                jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

                jPanel1.setBackground(new java.awt.Color(41, 45, 49));
                jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 180, Short.MAX_VALUE)
                );

                jLabel1.setFont(new java.awt.Font("sansserif", 2, 12)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(153, 153, 153));
                jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel1.setText("1400 Sokak No: 9/8 Baysak - 1 İş Merkezi Alsancak / İZMİR Tel: 0232 - 421 - 63 - 43 Fax: 0232 - 465 - 17 - 12 info@kontrolsis.com");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        private javax.swing.JButton jButton5;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JToolBar jToolBar1;
        // End of variables declaration//GEN-END:variables
}
